channels:
- conda-forge
dependencies:
- defusedxml =0.7.1
- coverage
- pandas =3.0.2
- pyyaml =6.0.3
- jinja2 =3.1.6
- paramiko =5.0.0
- tqdm =4.68.0
- hatchling =1.30.1
- hatch-vcs =0.5.0
- pydantic =2.13.4
