title: pysqa
author: Jan Janssen

execute:
  execute_notebooks           : off

repository:
  url                       : https://github.com/pyiron/pysqa
html:
  use_repository_button: true

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  config:
    autosummary_generate: True
    templates_path: ['_templates']
